# Change these first
owner: hoopybe # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Hoopy.be
    url: https://hoopy.be
  - name: FW
    url: $FW_SITE
  - name: FWA
    url: $FWA_SITE

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://hoopy.be/img/logo.png
  name: Hoopy Uptime
  introTitle: "**Hoopy** uptime monitor and status page"
  introMessage: "This data is updated automatically."
  navbar:
    - title: Status
      href: /
    - title: Hoopy.be
      href: https://hoopy.be

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
