# Change these first
owner: hoopybe # Your GitHub username
repo: uptime # Your GitHub repository name
assignees: hoopybe

# Add your sites here
sites:
  - name: Hoopy.be
    url: https://hoopy.be
  - name: Google 204
    url: https://google.com/generate_204
  - name: FW
    url: $FW_SITE
  - name: FWAw
    url: $FWA_SITE
  - name: FWM
    url: $FWM_SITE
  - name: F2000
    url: $F2000_SITE
  - name: FWAll
    url: $FWALL_SITE
  - name: FWB
    url: $FWB_SITE
  - name: CMG
    url: $CMG_SITE
  - name: EMYG
    url: $EMYG_SITE
  - name: PSI
    url: $PSI_SITE
  - name: LDP
    url: $LDP_SITE
  - name: GBZ
    url: $GBZ_SITE
  - name: BA
    url: $BA_SITE
  - name: TPB
    url: $TPB_SITE
  - name: BDH
    url: $BDH_SITE
  - name: BIBRU
    url: $BIBRU_SITE
  - name: EBS
    url: $EBS_SITE
    

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://hoopy.be/img/logo.png
  name: Hoopy.be Uptime
  introTitle: "**Hoopy.be** uptime monitor and status page"
  introMessage: "This data is updated automatically."
  navbar:
    - title: Status
      href: /
    - title: Hoopy.be
      href: https://hoopy.be

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
