# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Hoopy.be
    url: https://hoopy.be
  - name: Secret Site
    url: $SECRET_SITE

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://hoopy.be/img/logo.png
  name: Hoopy Uptime
  introTitle: "**Hoopy** open-source uptime monitor and status page"
  introMessage: "This data is updated automatically."
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
